apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-cert
  namespace: certmgr
spec:
  isCA: true
  commonName: ca-cert
  subject:
    organizations:
    - localhost
    organizationalUnits:
    - localhost
  secretName: ca-secret
  privateKey:
    algorithm: Ed25519
  issuerRef:
    name: self-signed-issuer
    kind: Issuer
    group: cert-manager.io
