apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: logs
  namespace: opentel
spec:
  image: otel/opentelemetry-collector-contrib
  mode: daemonset
  resources:
    limits: null
    requests:
      cpu: 10m
      memory: 10Mi
  volumeMounts:
  - name: pods
    mountPath: /var/log/pods
    readOnly: true
  volumes:
  - name: pods
    hostPath:
      path: /var/log/pods
  config:
    receivers:
      filelog:
        include:
        - /var/log/pods/*/*/*.log
        start_at: beginning

    exporters:
      loki:
        endpoint: http://loki.grafana:3100/loki/api/v1/push
        tls:
          insecure: true

    service:
      pipelines:
        logs:
          receivers: [filelog]
          exporters: [loki]
