global: # 7
  imageRegistry: docker.io

deploymentMode: SingleBinary # 59

loki: # 134
  auth_enabled: false # 447
  commonConfig: # 483
    replication_factor: 1
  storage: # 491
    type: filesystem
  schemaConfig: # 590
    configs:
    - from: 2025-01-01
      object_store: filesystem
      store: tsdb
      schema: v13
      index:
        prefix: index_
        period: 24h

test: # 691
  enabled: false

lokiCanary: # 721
  enabled: false

gateway: # 906
  enabled: false

singleBinary: # 1279
  replicas: 1 # 1281
  resources: # 1344
    limits: null
    requests:
      cpu: 10m
      memory: 10Mi
  persistence: # 1370
    size: 10Gi

write: # 1409
  replicas: 0

read: # 1559
  replicas: 0

backend: # 1704
  replicas: 0

memcached: # 3703
  enabled: false

resultsCache: # 3793
  enabled: false

chunksCache: # 3904
  enabled: false

sidecar: # 4237
  rules:
    enabled: false
