global: # 15
  imageRegistry: docker.io

primary: # 283
  resources: # 511
    limits: null
    requests:
      cpu: 10m
      memory: 10Mi
  persistence: # 604
    size: 10Gi

extraDeploy:
- |
  apiVersion: v1
  kind: Service
  metadata:
    name: mariadb-lb
    namespace: mariadb
    annotations:
      metallb.io/loadBalancerIPs: "fd64::99,192.168.64.99"
  spec:
    ipFamilyPolicy: RequireDualStack
    ports:
    - name: mysql
      port: 3306
      targetPort: mysql
    selector:
      app.kubernetes.io/component: primary
      app.kubernetes.io/instance: mariadb
      app.kubernetes.io/name: mariadb
    type: LoadBalancer
