global: # 15
  imageRegistry: docker.io

primary: # 283
  resources: # 511
    limits: null
    requests:
      cpu: 10m
      memory: 10Mi
  persistence: # 604
    size: 10Gi
  service: # 656
    type: LoadBalancer
    loadBalancerIP: 192.168.64.99
