controller: # 197
  image: # 203
    repository: quay.io/metallb/controller
  strategy: # 216
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  resources: # 230
    limits: null
    requests:
      cpu: 10m
      memory: 10Mi

speaker: # 262
  image: # 279
    repository: quay.io/metallb/speaker
  updateStrategy: # 286
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  resources: # 303
    limits: null
    requests:
      cpu: 10m
      memory: 10Mi
  frr: # 335
    enabled: false
