image: # 5
  repository: registry.k8s.io/metrics-server/metrics-server

fullnameOverride: metrics-server # 15

updateStrategy: # 82
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1

args: # 101
- --kubelet-insecure-tls

resources: # 173
  limits: null
  requests:
    cpu: 10m
    memory: 10Mi
