configmapReload: # 30
  prometheus:
    enabled: false

server: # 126
  image: # 194
    repository: quay.io/prometheus/prometheus
  configMapOverrideName: config # 367
  fullnameOverride: prometheus # 373
  persistentVolume: # 530
    size: 10Gi
  resources: # 698
    limits: null
    requests:
      cpu: 10m
      memory: 10Mi
  service: # 753
    loadBalancerIP: 192.168.64.91
    type: LoadBalancer
  retention: 1h # 802

alertmanager: # 1179
  enabled: false

kube-state-metrics: # 1222
  enabled: false

prometheus-node-exporter: # 1230
  enabled: false

prometheus-pushgateway: # 1244
  enabled: false
