configmapReload: # 30
  prometheus:
    enabled: false

server: # 126
  image: # 194
    repository: quay.io/prometheus/prometheus
  configMapOverrideName: config # 367
  fullnameOverride: prometheus # 373
  persistentVolume: # 530
    size: 10Gi
  resources: # 698
    limits: null
    requests:
      cpu: 10m
      memory: 10Mi
  service:
    enabled: false
  retention: 1h # 802

alertmanager: # 1179
  enabled: false

kube-state-metrics: # 1222
  enabled: false

prometheus-node-exporter: # 1230
  enabled: false

prometheus-pushgateway: # 1244
  enabled: false

extraManifests:
- |
  apiVersion: v1
  kind: Service
  metadata:
    name: prometheus
    namespace: grafana
    annotations:
      metallb.io/loadBalancerIPs: "fd64::91,192.168.64.91"
  spec:
    ipFamilyPolicy: RequireDualStack
    ports:
    - name: http
      port: 80
      targetPort: 9090
    selector:
      app.kubernetes.io/component: server
      app.kubernetes.io/instance: prometheus
      app.kubernetes.io/name: prometheus
    type: LoadBalancer
